name: HACS Action
on:
  pull_request:

jobs:
  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: "actions/checkout@v4"
      - name: Validate HACS
        uses: "hacs/action@main"
        with:
          category: "plugin"